# Generated by Django 4.2.1 on 2023-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/images/blank_pf.png', upload_to='static/images/'),
        ),
    ]
